# Generated by Django 3.2.15 on 2022-08-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220810_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
